### ISSUE TITLE
TODO till release

### ISSUE THREAD

**Issue by snmsts** [roswell/roswell2#2]
- [x] run/install sbcl-bin
- [ ] run/install ros script
- [x] config info store in system/user/local/current-dir seemlessly
